[project]
name = "xmsr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "wkrokosz", email = "w.krokosz@cent.uw.edu.pl" }
]
requires-python = ">=3.11"
dependencies = [
    "numpy>1.25",
    "xarray<2025.5.0",
    "zarr<3",
]

[build-system]
requires = ["uv_build>=0.8.23,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=6.30.1",
    "ruff>=0.13.3",
]
gui = [
    "qtpy>=2.4.3",
]
notebook = [
    "hvplot>=0.12.1",
]
